"""Walk-forward companion for parameterized Pine Script strategies."""

from pinewf.compare import (
    COMPARE_COLUMNS,
    HIGHER_IS_BETTER,
    LOWER_IS_BETTER,
    compare_metrics,
    compare_report,
    compare_summary,
)
from pinewf.engine import BacktestResult, StrategyConfig, run_backtest
from pinewf.metrics import buy_hold_metrics, compute_metrics
from pinewf.montecarlo import (
    MonteCarloConfig,
    equity_path_bands,
    load_trade_returns,
    monte_carlo_figure,
    percentile_bands,
    render_monte_carlo_png,
    run_monte_carlo,
    simulate_trade_returns,
)
from pinewf.pine_lint import (
    RULES,
    PineFinding,
    count_by_severity,
    findings_to_json,
    format_findings,
    lint_file,
    lint_source,
    worst_severity,
)
from pinewf.regime import (
    REGIME_ORDER,
    RegimeConfig,
    label_regimes,
    regime_breakdown,
    regime_buckets,
    regime_summary,
)
from pinewf.risk import (
    max_consecutive_losses,
    max_drawdown_duration_bars,
    risk_metrics,
    sortino_ratio,
    ulcer_index,
)
from pinewf.sensitivity import (
    SensitivityConfig,
    duration_buckets,
    duration_sensitivity,
    sensitivity_from_csv,
)
from pinewf.walk_forward import (
    WFWindow,
    consistency,
    rolling_windows,
    walk_forward_optimize,
    walk_forward_replay,
)

__all__ = [
    "BacktestResult",
    "COMPARE_COLUMNS",
    "HIGHER_IS_BETTER",
    "LOWER_IS_BETTER",
    "MonteCarloConfig",
    "PineFinding",
    "REGIME_ORDER",
    "RULES",
    "RegimeConfig",
    "SensitivityConfig",
    "StrategyConfig",
    "WFWindow",
    "buy_hold_metrics",
    "compare_metrics",
    "compare_report",
    "compare_summary",
    "compute_metrics",
    "consistency",
    "count_by_severity",
    "duration_buckets",
    "duration_sensitivity",
    "equity_path_bands",
    "findings_to_json",
    "format_findings",
    "label_regimes",
    "lint_file",
    "lint_source",
    "load_trade_returns",
    "max_consecutive_losses",
    "max_drawdown_duration_bars",
    "monte_carlo_figure",
    "percentile_bands",
    "regime_breakdown",
    "regime_buckets",
    "regime_summary",
    "render_monte_carlo_png",
    "risk_metrics",
    "rolling_windows",
    "run_backtest",
    "run_monte_carlo",
    "sensitivity_from_csv",
    "simulate_trade_returns",
    "sortino_ratio",
    "ulcer_index",
    "walk_forward_optimize",
    "walk_forward_replay",
    "worst_severity",
]
